### ISSUE TITLE
Android cannot run

### ISSUE THREAD

**Issue by NotMeanttoBe** [Ashrafty/RAE-VPN#2]
Hello, your Flutter project looks great, but when I tried running it on my Android phone, I encountered the following error. I'm not sure what's causing it. Could you help me troubleshoot this?

E/MethodChannel#flutter_v2ray(19954): java.lang.SecurityException: com.example.rae_vpn: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
E/MethodChannel#flutter_v2ray(19954): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3087)
E/MethodChannel#flutter_v2ray(19954): 	at android.os.Parcel.createException(Parcel.java:3071)
E/MethodChannel#flutter_v2ray(19954): 	at android.os.Parcel.readException(Parcel.java:3054)
E/MethodChannel#flutter_v2ray(19954): 	at android.os.Parcel.readException(Parcel.java:2996)
E/MethodChannel#flutter_v2ray(19954): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
E/MethodChannel#flutter_v2ray(19954): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1868)
E/MethodChannel#flutter_v2ray(19954): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1804)
E/MethodChannel#flutter_v2ray(19954): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:777)
E/MethodChannel#flutter_v2ray(19954): 	at com.github.blueboytm.flutter_v2ray.v2ray.V2rayController.init(V2rayController.java:35)
E/MethodChannel#flutter_v2ray(19954): 	at com.github.blueboytm.flutter_v2ray.FlutterV2rayPlugin.lambda$onAttachedToEngine$2$com-github-blueboytm-flutter_v2ray-FlutterV2rayPlugin(FlutterV2rayPlugin.java:69)
E/MethodChannel#flutter_v2ray(19954): 	at com.github.blueboytm.flutter_v2ray.FlutterV2rayPlugin$$ExternalSyntheticLambda2.onMethodCall(Unknown Source:4)
E/MethodChannel#flutter_v2ray(19954): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter_v2ray(19954): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#flutter_v2ray(19954): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter_v2ray(19954): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter_v2ray(19954): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#flutter_v2ray(19954): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter_v2ray(19954): 	at android.os.Looper.loopOnce(Looper.java:257)
E/MethodChannel#flutter_v2ray(19954): 	at android.os.Looper.loop(Looper.java:368)
E/MethodChannel#flutter_v2ray(19954): 	at android.app.ActivityThread.main(ActivityThread.java:8819)
E/MethodChannel#flutter_v2ray(19954): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_v2ray(19954): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
E/MethodChannel#flutter_v2ray(19954): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
E/MethodChannel#flutter_v2ray(19954): Caused by: android.os.RemoteException: Remote stack trace:
E/MethodChannel#flutter_v2ray(19954): 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14900)
E/MethodChannel#flutter_v2ray(19954): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
E/MethodChannel#flutter_v2ray(19954): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3005)
E/MethodChannel#flutter_v2ray(19954): 	at android.os.Binder.execTransactInternal(Binder.java:1387)
E/MethodChannel#flutter_v2ray(19954): 	at android.os.Binder.execTransact(Binder.java:1299)
E/MethodChannel#flutter_v2ray(19954): 
E/flutter (19954): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter (19954): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (19954): <asynchronous suspension>
E/flutter (19954): #2      MethodChannelFlutterV2ray.initializeV2Ray (package:flutter_v2ray/flutter_v2ray_method_channel.dart:30:5)
E/flutter (19954): <asynchronous suspension>
E/flutter (19954): #3      FlutterV2ray.initializeV2Ray (package:flutter_v2ray/flutter_v2ray.dart:33:5)
E/flutter (19954): <asynchronous suspension>
E/flutter (19954): #4      V2RayService.initializeV2Ray (package:rae_vpn/v2ray_service.dart:33:5)
E/flutter (19954): <asynchronous suspension>
E/flutter (19954): #5      main (package:rae_vpn/main.dart:7:3)
E/flutter (19954): <asynchronous suspension>

**Comment by Ashrafty** [comment]
what flutter version are you using

**Comment by NotMeanttoBe** [comment]
this is my Flutter version
Flutter 3.22.2  ols • Dart 3.4.3 • DevTools 2.34.3

**Comment by Ashrafty** [comment]
downgrade to flutter 3.19.5 it will work just fine

**Comment by NotMeanttoBe** [comment]
Thank you for your reply. I have now downgraded to 3.19.5 and it runs perfectly. Will you consider developing projects for iOS connection in the future?

**Comment by Ashrafty** [comment]
i do not have a mac os machine so i can't do anything about it. if i had tho i would develop it
